
###
GET http://localhost:9000/api/users?limit=10

### 
GET http://localhost:9000/api/user/1

###
POST http://localhost:9000/api/user
Content-Type: application/json

{
      "first_name": "sparrow",
      "last_name": "jack",
      "password": "lol1",
      "email": "jack@gmail.com",
      "birth_date": "1999-05-19"

}

###
DELETE http://localhost:9000/api/user/1

###
PUT http://localhost:9000/api/user/1
Content-Type: application/json

{
      "first_name": "lol1"
}